### ISSUE TITLE
MakeFile Spelling error 

### ISSUE THREAD

**Issue by dookofcrds** [DefNu1l/Batleth#1]
> __

**Comment by DefNu1l** [comment]
> hey just so you know you wrote "cpanm" where it should be just "cpan" :)

Do you have any execution errors with cpanm. It's actually not an spelling failure.

**Comment by dookofcrds** [comment]
my bad dude I was stoned as, thought I was helpful , (⁠*⁠_⁠*⁠)

**Comment by DefNu1l** [comment]
> my bad dude I was stoned as, thought I was helpful , (⁠_⁠_⁠_⁠)

Haha, okay. Thanks anyway for your cooperation :)
